#!/bin/bash
#SBATCH -N 1
#SBATCH -n 68
#SBATCH -C knl,quad,cache
#SBATCH --job-name=UoI_Debug
#SBATCH --output=./debug/stdout.log
#SBATCH --error=./debug/stderr.log 
#SBATCH -t 00:30:00
#SBATCH -q debug

module load gsl
module load eigen3
module load cray-hdf5-parallel
module load boost


exe=./uoi
input=/global/cscratch1/sd/mbalasu2/data0.h5


OMP_NUM_THREADS=4
OMP_PROC_BIND=spread


srun -n 68 -c 4 --cpu_bind=threads -u $exe -f $input -v 1  --output_coef ./coef_.h5 --output_scores ./scores_.h5 --dataset_matrix /X --dataset_vector /y
